### ISSUE TITLE
Ошибка при вводе числа 7700

### ISSUE THREAD

**Issue by andrey-helldar** [andrey-helldar/DigitText#3]

**Comment by andrey-helldar** [comment]
При тестировании ошибок не было обнаружено.

**Comment by dkulyk** [comment]
Включите Notice и попробуйте снова, "PHP error:  Undefined offset: 0 in ..."
Он возникает когда 0 в десятках.
А также проблема с расчетом когда 10-19 c сотнями.

**Comment by Akellacom** [comment]
Такая же фигня.

**Comment by andrey-helldar** [comment]
Это может показаться странным, но ни под виндой, ни под линуксом какие бы типы нотификации ни ставил - ни разу не поймал данной ошибки. Отрабатывает всё верно и ни строчки в лог не пишет, ибо ошибок не находит.
